[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["echo 'Backend build complete'"]

[start]
cmd = "cd backend && python3 -m uvicorn api.main:app --host 0.0.0.0 --port $PORT"
