# Network Configuration
network:
  name: "base"
  rpc_url: "${BASE_RPC_URL}"
  chain_id: 8453
  gas_price_gwei: 0.1  # Base has low gas fees
  max_gas_price_gwei: 1.0

# Uniswap V3 Configuration
uniswap:
  factory_address: "${UNISWAP_V3_FACTORY}"
  router_address: "${UNISWAP_V3_ROUTER}"
  position_manager_address: "${UNISWAP_V3_POSITION_MANAGER}"
  quoter_address: "${UNISWAP_V3_QUOTER}"

# Strategy Configuration
strategy:
  # Type: "concentrated_follower", "multi_position", "multi_pool"
  type: "concentrated_follower"
  
  # Rebalancing
  rebalance_threshold: 0.05  # Rebalance when price moves 5% from center
  min_rebalance_interval_hours: 1  # Minimum time between rebalances
  
  # Position sizing
  position_concentration: 0.5  # 0-1, higher = more concentrated around price
  min_tick_range: 50  # Minimum tick range for positions
  max_tick_range: 1000  # Maximum tick range
  
  # Gas management
  max_gas_cost_ratio: 0.02  # Max 2% of position value
  gas_buffer_multiplier: 1.2  # 20% buffer on gas estimates

# Risk Management
risk:
  max_position_size_usd: 10000
  max_positions_per_pool: 5
  max_slippage: 0.005  # 0.5%
  emergency_exit_threshold: 0.30  # Exit if price moves 30% suddenly

# Data Collection
data:
  price_update_interval_seconds: 60
  historical_data_days: 30
  volatility_window_hours: 24

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "logs/optimizer.log"
  console: true
