# Pool Configurations for Uniswap V3 on Base
# Add pools you want to provide liquidity to

pools:
  # Base Sepolia Testnet Pools
  - name: "WETH-USDC"
    address: "0x94bfc0574FF48E92cE43d495376C477B1d0EEeC0"  # Uniswap V3 on Base Sepolia
    token0: "WETH"
    token1: "USDC"
    token0_address: "0x4200000000000000000000000000000000000006"  # WETH on Base Sepolia
    token1_address: "0x036CbD53842c5426634e7929541eC2318f3dCF7e"  # USDC on Base Sepolia
    fee_tier: 500  # 0.05%
    decimals0: 18
    decimals1: 6
    priority: 1  # Higher = allocate more capital
    enabled: true
    
  - name: "WETH-USDbC"
    address: "0x4C36388bE6F416A29C8d8Eee81C771cE6bE14B18"  # USDbC pool
    token0: "WETH"
    token1: "USDbC"
    token0_address: "0x4200000000000000000000000000000000000006"
    token1_address: "0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA"  # USDbC (Bridged USDC)
    fee_tier: 500
    decimals0: 18
    decimals1: 6
    priority: 2
    enabled: true
    
  - name: "WETH-DAI"
    address: "0x..."  # Update with actual pool address
    token0: "WETH"
    token1: "DAI"
    token0_address: "0x4200000000000000000000000000000000000006"
    token1_address: "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb"  # DAI on Base
    fee_tier: 500
    decimals0: 18
    decimals1: 18
    priority: 3
    enabled: false
    
  - name: "WETH-cbBTC"
    address: "0x..."  # Update with actual pool address
    token0: "WETH"
    token1: "cbBTC"
    token0_address: "0x4200000000000000000000000000000000000006"
    token1_address: "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"  # Coinbase Wrapped BTC
    fee_tier: 3000  # 0.3% for more volatile pairs
    decimals0: 18
    decimals1: 8
    priority: 4
    enabled: false
    
  - name: "USDC-USDbC"
    address: "0x..."  # Update with actual pool address
    token0: "USDC"
    token1: "USDbC"
    token0_address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    token1_address: "0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA"
    fee_tier: 100  # 0.01% for stablecoin pairs
    decimals0: 6
    decimals1: 6
    priority: 5
    enabled: false
