# Pool Configurations
# Add pools you want to provide liquidity to

pools:
  - name: "AVAX-USDC"
    address: "0x..."  # Update with actual pool address
    token0: "WAVAX"
    token1: "USDC"
    token0_address: "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7"
    token1_address: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E"
    fee_tier: 3000  # 0.3%
    decimals0: 18
    decimals1: 6
    priority: 1  # Higher = allocate more capital
    enabled: true
    
  - name: "AVAX-USDT"
    address: "0x..."
    token0: "WAVAX"
    token1: "USDT"
    token0_address: "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7"
    token1_address: "0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7"
    fee_tier: 3000
    decimals0: 18
    decimals1: 6
    priority: 2
    enabled: true
    
  - name: "AVAX-BTC.b"
    address: "0x..."
    token0: "WAVAX"
    token1: "BTC.b"
    token0_address: "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7"
    token1_address: "0x152b9d0FdC40C096757F570A51E494bd4b943E50"
    fee_tier: 3000
    decimals0: 18
    decimals1: 8
    priority: 3
    enabled: false
    
  - name: "USDC-USDT"
    address: "0x..."
    token0: "USDC"
    token1: "USDT"
    token0_address: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E"
    token1_address: "0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7"
    fee_tier: 500  # 0.05% for stablecoin pairs
    decimals0: 6
    decimals1: 6
    priority: 4
    enabled: false
